### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by ghost** [samwilson/asset-manager#3]
Hello, I'm relatively new to PHP. After deploying this on my apache server with mod_rewrite enabled, and the MySQL database populated, this error appears on the main page. Could you point me in the right direction?

https://gyazo.com/94e4695f346c4fca7a36229ce9acfaf2

**Comment by samwilson** [comment]
I'm afraid this project is no longer maintained. Sorry!

Feel free to fork it and improve it if you like.
